"""empty message

Revision ID: 427da589e48e
Revises: f8d032e23ac6
Create Date: 2023-04-24 10:34:54.225997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427da589e48e'
down_revision = 'f8d032e23ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('value', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=True))
        batch_op.drop_column('action')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    op.drop_table('settings')
    # ### end Alembic commands ###
